---

- name: (Handler) Start/reload NGINX
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: true
  listen: (Handler) Run NGINX

- name: (Handler) Start/reload MARIADB
  ansible.builtin.service:
    name: mariadb
    state: restarted
    enabled: true
  listen: (Handler) Run MARIADB

- name: (Handler) Start/reload PHP-FPM
  ansible.builtin.service:
    name: "{{ php_fpm_daemon }}"
    state: restarted
    enabled: true
  listen: (Handler) Run PHP-FPM