---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
platforms:
  - name: debian-bookworm
    image: geerlingguy/docker-debian12-ansible:latest
    privileged: true

  - name: ubuntu-2204
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    privileged: true

  - name: rockylinux-9
    image: geerlingguy/docker-rockylinux9-ansible:latest
    privileged: true
