---

- name: Ensure that nginx directories exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
  with_items:
    - "{{ nginx_backend_root }}"
    - "{{ nginx_frontend_root }}"
    - "{{ nginx_sites_available_dir }}"
    - "{{ nginx_sites_enabled_dir }}"

- name: Ensure group "www-data" exists
  ansible.builtin.group:
    name: www-data
    state: present

- name: Ensure user "www-data" exists
  ansible.builtin.user:
    name: www-data
    group: www-data
    state: present

- name: Delete default nginx host
  ansible.builtin.file:
    path: "{{ nginx_sites_enabled_dir }}/default"
    state: absent
  notify: (Handler) Run NGINX

- name: Write the nginx config file
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "{{ nginx_config_dir }}/nginx.conf"
    owner: root
    group: root
    mode: 0644
  notify: (Handler) Run NGINX

- name: Write the nginx backend vhost config file
  ansible.builtin.template:
    src: nginx-backend.conf.j2
    dest: "{{ nginx_sites_available_dir }}/{{ host_backend_fqdn }}"
    owner: root
    group: root
    mode: 0644
  register: nginx_backend_config

- name: Enable the nginx backend vhost
  shell: "ln -sf {{ nginx_sites_available_dir }}/{{ host_backend_fqdn }} {{ nginx_sites_enabled_dir }}"
  when: nginx_backend_config.changed
  notify: (Handler) Run NGINX

- name: Write the nginx frontend vhost config file
  ansible.builtin.template:
    src: nginx-frontend.conf.j2
    dest: "{{ nginx_sites_available_dir }}/{{ host_frontend_fqdn }}"
    owner: root
    group: root
    mode: 0644
  register: nginx_frontend_config

- name: Enable the nginx frontend vhost
  ansible.builtin.shell: "ln -sf {{ nginx_sites_available_dir }}/{{ host_frontend_fqdn }} {{ nginx_sites_enabled_dir }}"
  when: nginx_frontend_config.changed
  notify: (Handler) Run NGINX